builds:
  - binary: container-builder-local-api
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - 386
archive:
  format: zip
  name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  files:
    - README.md
release:
  github:
    owner: zaru
    name: container-builder-local-api